/**
 * Q1.3 — injects social/head metadata into the exported web shell (dist/index.html).
 *
 *   npm run build:web    (expo export -p web && node scripts/injectWebHead.mjs)
 *
 * WHY THIS EXISTS: the shell's <head> is generated by @expo/cli's internal template and the repo
 * owns no override (no expo-router, so no +html.tsx). The export ships title + theme-color +
 * favicon and nothing else — so every invite link shared into WhatsApp/iMessage/Slack unfurled
 * as a bare "T Poker" with no description and no image.
 *
 * NOT an indexing change: app.tpoker.app is deliberately `noindex` (vercel.json). Open Graph is
 * read by link unfurlers, not by the search index, so richer sharing and de-indexing coexist —
 * and there is intentionally NO canonical tag here, which would be meaningless on a noindex host.
 *
 * Idempotent: re-running replaces the injected block rather than duplicating it.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const INDEX = resolve(here, '../dist/index.html');

const SITE = 'https://tpoker.app';
const APP = 'https://app.tpoker.app';
// EDUCATION-FIRST, mirroring the store listing and the landing description — this text unfurls
// wherever an invite link is shared, so it is a store-classification surface, not just marketing.
// The first draft led with the ledger ("Run the night and study the game…") and dropped the
// not-a-gambling-product line; both are required by the standing posture.
const TITLE = 'T Poker — learn poker strategy, keep score at home games';
const DESCRIPTION =
  'Learn poker strategy with lessons, a daily quiz and decision drills — and keep the buy-in ledger for your home game, settled in the fewest transfers. Not a gambling product: no wagering, no money in the app. 18+.';
const OG_IMAGE = `${SITE}/og.png`;

const START = '<!-- injected-head:start -->';
const END = '<!-- injected-head:end -->';

const block = `${START}
    <meta name="description" content="${DESCRIPTION}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="T Poker" />
    <meta property="og:title" content="${TITLE}" />
    <meta property="og:description" content="${DESCRIPTION}" />
    <meta property="og:url" content="${APP}/" />
    <meta property="og:image" content="${OG_IMAGE}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${TITLE}" />
    <meta name="twitter:description" content="${DESCRIPTION}" />
    <meta name="twitter:image" content="${OG_IMAGE}" />
    ${END}`;

if (!existsSync(INDEX)) {
  throw new Error(`injectWebHead: ${INDEX} not found — run \`expo export -p web\` first`);
}

let html = readFileSync(INDEX, 'utf8');

// Replace a previous injection if present (idempotent re-runs).
const existing = new RegExp(`${START}[\\s\\S]*?${END}`);
html = existing.test(html) ? html.replace(existing, block) : html.replace('</head>', `  ${block}\n  </head>`);

if (!html.includes(START)) throw new Error('injectWebHead: no </head> found — export template changed');

writeFileSync(INDEX, html);
console.log('injected head metadata into dist/index.html (description + OG + Twitter)');
