/**
 * Cross-language hash reconciliation (resolves R1): the workbook exporter's canonicalization
 * (tools/content-export/canonical.py) must produce the SAME content_hash as the app's hash.ts.
 * The fixture is generated by `python tools/content-export/make_fixture.py`.
 */
import { contentHash } from '../hash';
import { hashFixture } from './hashFixture';

describe('exporter ↔ app hash parity (R1)', () => {
  it('hash.ts matches the Python exporter hash for the shared fixture', () => {
    const h = contentHash({ rows: hashFixture.rows as any, schema: hashFixture.schema as any });
    expect(h).toBe(hashFixture.contentHash);
  });
});
