// AUTO-GENERATED by tools/content-export/make_fixture.py — DO NOT EDIT.
// Cross-language hash fixture: pins canonical.py (exporter) == hash.ts (app). Resolves R1.
export const hashFixture = {
  "schema": [
    {
      "column": "RowID",
      "datatype": "string"
    },
    {
      "column": "Freq",
      "datatype": "number"
    },
    {
      "column": "Att",
      "datatype": "int"
    },
    {
      "column": "Note",
      "datatype": "string"
    },
    {
      "column": "Opt",
      "datatype": "string"
    }
  ],
  "rows": [
    {
      "RowID": "R2",
      "Freq": 92.5,
      "Att": 20,
      "Note": "b",
      "Opt": null
    },
    {
      "RowID": "R1",
      "Freq": 100.0,
      "Att": 3,
      "Note": "a",
      "Opt": "x"
    },
    {
      "RowID": "R3",
      "Freq": 2.5,
      "Att": 0,
      "Note": "",
      "Opt": null
    }
  ],
  "contentHash": "f0a54ab768fc548e9c85d8511750a792aa58250c069c4e8eeaa474e82d2a3c18"
} as const;
