/**
 * Coach grounding — pure logic over the exported `coach_grounding.json` artifact
 * (workbook 0.8.1, generated by tools/content-export; never the workbook directly).
 *
 * THE HONESTY SEAM lives here: a grounded numeric/qualitative claim is only ever
 * surfaced to the coach AS FACT through `assertion()`, which returns the verbatim
 * `assertion_template` IFF `safe_to_assert === true`. Anything else (unsafe, malformed,
 * empty template) yields `null` — the coach must not assert it. No fabrication: every
 * field (claim text, verification tier, citation, caveat) is copied verbatim from the
 * artifact; this module never invents claims or loosens a tier.
 */

/** One grounded claim — mirrors a row of the exported `coach_grounding.json`. */
export interface GroundedClaim {
  grounding_id: string;
  concept_id: string;
  claim_text: string;
  numeric_value: number | null;
  unit: string;
  evidence_node_ids: string[];
  evidence_sheet: string;
  verification_tier: string;
  confidence_level: string;
  confidence_score: number;
  evidence_count: number;
  citation: string;
  /** Verbatim caveat-bearing sentence the coach may assert when safe_to_assert. */
  assertion_template: string;
  grounding_type: string;
  /** Governance gate: only `true` claims may be served as fact. */
  safe_to_assert: boolean;
}

/** The exported artifact envelope. */
export interface GroundingDataset {
  dataset_version: string;
  claims: GroundedClaim[];
}

/** Indexed, read-optimized view of the dataset. */
export interface GroundingIndex {
  datasetVersion: string;
  /** Every well-formed claim (assertable or not). */
  all: GroundedClaim[];
  /** concept_id → claims (insertion order preserved). */
  byConcept: Map<string, GroundedClaim[]>;
  /** grounding_id → claim. */
  byId: Map<string, GroundedClaim>;
}

const isNonEmptyString = (v: unknown): v is string => typeof v === 'string' && v.length > 0;

/** A claim is well-formed enough to index if it has the identifying + gate fields. */
function isWellFormed(c: unknown): c is GroundedClaim {
  if (!c || typeof c !== 'object') return false;
  const r = c as Record<string, unknown>;
  return (
    isNonEmptyString(r.grounding_id) &&
    isNonEmptyString(r.concept_id) &&
    isNonEmptyString(r.claim_text) &&
    typeof r.safe_to_assert === 'boolean' &&
    typeof r.assertion_template === 'string'
  );
}

/**
 * Build the index from a parsed dataset. Malformed claims are dropped (not fabricated
 * into shape); duplicate grounding_ids keep the first occurrence. Tolerant of a missing
 * or non-array `claims` (returns an empty index) so a bad artifact never throws upstream.
 */
export function buildGroundingIndex(data: GroundingDataset | null | undefined): GroundingIndex {
  const datasetVersion = isNonEmptyString(data?.dataset_version) ? data!.dataset_version : 'unknown';
  const byConcept = new Map<string, GroundedClaim[]>();
  const byId = new Map<string, GroundedClaim>();
  const all: GroundedClaim[] = [];

  const rows = Array.isArray(data?.claims) ? data!.claims : [];
  for (const row of rows) {
    if (!isWellFormed(row)) continue;
    if (byId.has(row.grounding_id)) continue;
    byId.set(row.grounding_id, row);
    all.push(row);
    const bucket = byConcept.get(row.concept_id);
    if (bucket) bucket.push(row);
    else byConcept.set(row.concept_id, [row]);
  }

  return { datasetVersion, all, byConcept, byId };
}

/** Whether this claim may be served to the user as fact. The single source of truth. */
export function isAssertable(claim: GroundedClaim | null | undefined): boolean {
  return !!claim && claim.safe_to_assert === true && isNonEmptyString(claim.assertion_template);
}

/**
 * The verbatim, caveat-bearing sentence the coach may state as fact — or `null` when the
 * claim is not safe to assert. NEVER returns `claim_text` for an unsafe claim; the gate
 * is `isAssertable`. This is the only function that turns a grounded claim into an assertion.
 */
export function assertion(claim: GroundedClaim | null | undefined): string | null {
  return isAssertable(claim) ? claim!.assertion_template : null;
}

/** All indexed claims for a concept (assertable or not) — for lookup/inspection. */
export function claimsForConcept(index: GroundingIndex | null, conceptId: string): GroundedClaim[] {
  if (!index) return [];
  return index.byConcept.get(conceptId) ?? [];
}

/** Only the claims for a concept that are safe to assert. */
export function assertableClaimsForConcept(index: GroundingIndex | null, conceptId: string): GroundedClaim[] {
  return claimsForConcept(index, conceptId).filter(isAssertable);
}

/** Look up one claim by its grounding id. */
export function claimById(index: GroundingIndex | null, groundingId: string): GroundedClaim | null {
  if (!index) return null;
  return index.byId.get(groundingId) ?? null;
}

/** Every safe-to-assert claim across the dataset. */
export function allAssertableClaims(index: GroundingIndex | null): GroundedClaim[] {
  if (!index) return [];
  return index.all.filter(isAssertable);
}

/**
 * Display-safe projection of an assertable claim — the verbatim caveat-bearing `assertion` (via the gate),
 * plus the verification tier + citation (verbatim metadata). This is what a "grounded references" surface
 * shows. It is NOT tied to any specific hand/analysis. Returns null for non-assertable claims.
 */
export interface GroundedAssertion {
  groundingId: string;
  conceptId: string;
  /** The safe, caveat-bearing sentence (from the assertion gate) — the only fact text surfaced. */
  assertion: string;
  tier: string;
  citation: string;
  unit: string;
  numericValue: number | null;
}

export function toAssertion(claim: GroundedClaim | null | undefined): GroundedAssertion | null {
  const a = assertion(claim);
  if (a === null || !claim) return null;
  return {
    groundingId: claim.grounding_id,
    conceptId: claim.concept_id,
    assertion: a,
    tier: claim.verification_tier,
    citation: claim.citation,
    unit: claim.unit,
    numericValue: claim.numeric_value,
  };
}

/** All safe-to-assert claims across the dataset, projected for display (assertion + tier + citation). */
export function allAssertions(index: GroundingIndex | null): GroundedAssertion[] {
  return allAssertableClaims(index)
    .map(toAssertion)
    .filter((x): x is GroundedAssertion => x !== null);
}
