import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { API_BASE_URL } from '../api/config';
import * as SecureStore from './storage';
import { PlayerBalanceDto } from '../api/sessionsApi';
import { SettlementDto } from '../api/settlementsApi';

export async function exportSessionCsv(sessionId: string, sessionName: string): Promise<void> {
  const token = await SecureStore.getItemAsync('accessToken');
  if (!token) throw new Error('Not authenticated');

  const url = `${API_BASE_URL}/api/sessions/${sessionId}/export`;
  const fileName = `session-${sessionName.replace(/\s+/g, '-')}.csv`;
  const destFile = new File(Paths.cache, fileName);

  const downloaded = await File.downloadFileAsync(url, destFile, {
    headers: { Authorization: `Bearer ${token}` },
    idempotent: true,
  });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) throw new Error('Sharing is not available on this device.');

  await Sharing.shareAsync(downloaded.uri, {
    mimeType: 'text/csv',
    dialogTitle: `Export: ${sessionName}`,
    UTI: 'public.comma-separated-values-text',
  });
}

export async function shareSessionCard(
  sessionName: string,
  groupName: string,
  date: string,
  duration: string,
  players: PlayerBalanceDto[],
  settlements: SettlementDto[],
  highlights?: string[],
): Promise<void> {
  const sorted = [...players].sort((a, b) => b.profitLoss - a.profitLoss);
  const html = buildCardHtml(sessionName, groupName, date, duration, sorted, settlements, highlights);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) throw new Error('Sharing is not available on this device.');
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Session Results' });
}

function fmtPL(n: number): string {
  const abs = Math.abs(Math.round(n));
  return `${n >= 0 ? '+' : '-'}₪${abs.toLocaleString()}`;
}

function buildCardHtml(
  sessionName: string,
  groupName: string,
  date: string,
  duration: string,
  players: PlayerBalanceDto[],
  settlements: SettlementDto[],
  highlights?: string[],
): string {
  const playerRows = players.map((p, i) => {
    const pl = p.profitLoss;
    const color = pl > 0 ? '#27AE60' : pl < 0 ? '#E74C3C' : '#7A8A99';
    return `<tr>
      <td style="color:#7A8A99;padding:6px 8px">#${i + 1}</td>
      <td style="padding:6px 8px;font-weight:600">${p.username}${i === 0 ? ' 🏆' : ''}</td>
      <td style="padding:6px 8px;color:#7A8A99">₪${Math.round(p.totalBuyIn).toLocaleString()}</td>
      <td style="padding:6px 8px;font-weight:700;color:${color}">${fmtPL(pl)}</td>
    </tr>`;
  }).join('');

  const settlementRows = settlements.map(s => `<tr>
    <td style="padding:5px 8px;color:#C9A84C;font-weight:600">${s.payerName}</td>
    <td style="padding:5px 8px;color:#7A8A99">→</td>
    <td style="padding:5px 8px;font-weight:600">${s.receiverName}</td>
    <td style="padding:5px 8px;font-weight:700;color:#C9A84C">₪${Math.round(s.amount).toLocaleString()}</td>
  </tr>`).join('');

  const settlementsBlock = settlements.length > 0
    ? `<div class="card"><h2>Settlements</h2><table><tbody>${settlementRows}</tbody></table></div>`
    : `<div class="card" style="text-align:center"><h2>Settlements</h2><div style="color:#27AE60;font-size:18px;font-weight:700">✓ Everyone is even</div></div>`;

  const highlightsBlock = highlights && highlights.length > 0
    ? `<div class="card">
         <h2>Highlights</h2>
         <ul style="margin:0;padding-left:18px;list-style:none">
           ${highlights.map(h => `<li style="padding:4px 0;font-size:13px;color:#E8EDF2;position:relative">
             <span style="position:absolute;left:-14px;color:#C9A84C;font-size:11px">•</span>${h}
           </li>`).join('')}
         </ul>
       </div>`
    : '';

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<style>
  body{font-family:-apple-system,Helvetica,sans-serif;background:#0F1923;color:#FFF;margin:0;padding:24px}
  .header{text-align:center;margin-bottom:24px}
  .suit{font-size:40px;margin-bottom:8px}
  h1{font-size:22px;font-weight:800;margin:0 0 4px;color:#FFF}
  .meta{color:#7A8A99;font-size:13px}
  .card{background:#1A2535;border-radius:12px;padding:16px;margin-bottom:16px;border:1px solid #243447}
  h2{font-size:11px;font-weight:600;color:#7A8A99;text-transform:uppercase;letter-spacing:0.8px;margin:0 0 12px}
  table{width:100%;border-collapse:collapse}
  td{font-size:14px;color:#FFF}
  .footer{text-align:center;color:#3A4A5A;font-size:11px;margin-top:24px}
</style>
</head>
<body>
<div class="header">
  <div class="suit">♠</div>
  <h1>${sessionName}</h1>
  <div class="meta">${groupName}  ·  ${date}  ·  ${duration}</div>
</div>
${highlightsBlock}
<div class="card"><h2>Results</h2><table><tbody>${playerRows}</tbody></table></div>
${settlementsBlock}
<div class="footer">Generated by PokerHome</div>
</body></html>`;
}
