"""Generate the cross-language hash fixture that pins canonical.py == app's hash.ts (resolves R1).
Writes a TS module the jest test imports. Run: python tools/content-export/make_fixture.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from canonical import content_hash

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "apps", "poker-mobile", "src", "content", "__tests__", "hashFixture.ts")

schema = [
    {"column": "RowID", "datatype": "string"},
    {"column": "Freq", "datatype": "number"},
    {"column": "Att", "datatype": "int"},
    {"column": "Note", "datatype": "string"},
    {"column": "Opt", "datatype": "string"},
]
rows = [
    {"RowID": "R2", "Freq": 92.5, "Att": 20, "Note": "b", "Opt": None},
    {"RowID": "R1", "Freq": 100.0, "Att": 3, "Note": "a", "Opt": "x"},
    {"RowID": "R3", "Freq": 2.5, "Att": 0, "Note": "", "Opt": None},
]
h = content_hash(rows, [c["column"] for c in schema])
ts = (
    "// AUTO-GENERATED by tools/content-export/make_fixture.py — DO NOT EDIT.\n"
    "// Cross-language hash fixture: pins canonical.py (exporter) == hash.ts (app). Resolves R1.\n"
    "export const hashFixture = " + json.dumps({"schema": schema, "rows": rows, "contentHash": h}, ensure_ascii=False, indent=2) + " as const;\n"
)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(ts)
print("python content_hash =", h)
print("wrote", OUT)
