/**
 * Bundled content packs (PR #5) — the in-app set the ContentStore ingests when the `content` flag is ON.
 *
 * Currently a quiz SAMPLE only (a deterministic, verbatim cross-section of Quiz_Bank generated by
 * tools/content-export/make_quiz_sample.py). The FULL quiz set (~4.5 MB) and other packs are a deferred
 * bundling decision (size/ops) — see docs. require() is inside the function so nothing is pulled into
 * the bundle's load path until bootstrap (itself flag-gated) calls this; a missing artifact → [].
 */
import type { ContentPack } from './types';
import { quizSamplePackArtifact } from './bundledArtifacts';

// Gated by the caller: the only invoker is bootstrapContent(), which returns early when the `content`
// flag is OFF — so this (and its require()) never runs in production. Keep that contract if adding callers.
export function bundledPacks(): ContentPack[] {
  const packs: ContentPack[] = [];
  try {
    packs.push(quizSamplePackArtifact() as ContentPack);
  } catch {
    /* artifact not bundled → no quizzes (runner shows an honest empty state) */
  }
  return packs;
}
