/**
 * Bundled content packs (PR #5) — the in-app set the ContentStore ingests when the `content` flag is ON.
 *
 * Currently a quiz SAMPLE only (a deterministic, verbatim cross-section of Quiz_Bank generated by
 * tools/content-export/make_quiz_sample.py). The FULL quiz set (~4.5 MB) and other packs are a deferred
 * bundling decision (size/ops) — see docs. require() is inside the function so nothing is pulled into
 * the bundle's load path until bootstrap (itself flag-gated) calls this; a missing artifact → [].
 */
import type { ContentPack } from './types';

export function bundledPacks(): ContentPack[] {
  const packs: ContentPack[] = [];
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    packs.push(require('../../assets/content/0.8.0/quiz_sample.pack.json') as ContentPack);
  } catch {
    /* artifact not bundled → no quizzes (runner shows an honest empty state) */
  }
  return packs;
}
