/**
 * Coach grounding consumer tests (PR #4).
 *
 * Proves the honesty seam: the coach only ever serves a claim as fact when
 * `safe_to_assert === true`, the loader is inert when the content flag is OFF, and the
 * bundled artifact indexes/looks-up correctly. Uses the REAL exported artifact for the
 * property test so the guarantee holds against actual workbook-derived data.
 */
jest.mock('../../../../config/features', () => ({ isFeatureEnabled: jest.fn() }));

import { isFeatureEnabled } from '../../../../config/features';
import { loadGroundingIndex, __resetGroundingCacheForTests } from '../groundingStore';
import {
  buildGroundingIndex,
  assertion,
  isAssertable,
  claimsForConcept,
  assertableClaimsForConcept,
  claimById,
  allAssertableClaims,
  type GroundedClaim,
  type GroundingDataset,
} from '../../logic/grounding';

// The real bundled artifact (generated by tools/content-export from workbook 0.8.0).
// require() (not import) avoids resolveJsonModule + a multi-thousand-line literal type in tsc.
const realArtifact = require('../../../../../assets/content/0.8.0/coach_grounding.json') as GroundingDataset;

const mockFlag = isFeatureEnabled as jest.Mock;

const claim = (over: Partial<GroundedClaim> = {}): GroundedClaim => ({
  grounding_id: 'CG-T1',
  concept_id: 'CK-T',
  claim_text: 'UTG opens ~13.4% (RFI)',
  numeric_value: 13.4,
  unit: '%',
  evidence_node_ids: ['RNG-0001'],
  evidence_sheet: 'Range_Viewer_Database',
  verification_tier: 'Calibrated',
  confidence_level: 'High',
  confidence_score: 75,
  evidence_count: 1,
  citation: 'Derived from calibrated ranges',
  assertion_template: 'UTG opens ~13.4% (RFI) (Calibrated; source: …). Not solver-exact.',
  grounding_type: 'Quantitative',
  safe_to_assert: true,
  ...over,
});

describe('assertion() — the honesty seam', () => {
  it('returns the verbatim template only when safe_to_assert', () => {
    const c = claim();
    expect(assertion(c)).toBe(c.assertion_template);
  });

  it('returns null for an unsafe claim — and never leaks claim_text', () => {
    const unsafe = claim({ safe_to_assert: false });
    expect(assertion(unsafe)).toBeNull();
    expect(assertion(unsafe)).not.toBe(unsafe.claim_text);
  });

  it('returns null for a safe claim with an empty template (nothing to assert)', () => {
    expect(assertion(claim({ assertion_template: '' }))).toBeNull();
    expect(isAssertable(claim({ assertion_template: '' }))).toBe(false);
  });

  it('handles null/undefined defensively', () => {
    expect(assertion(null)).toBeNull();
    expect(assertion(undefined)).toBeNull();
    expect(isAssertable(null)).toBe(false);
  });
});

describe('buildGroundingIndex — real artifact (95 claims)', () => {
  const index = buildGroundingIndex(realArtifact);

  it('loads the dataset version and all claims, with unique grounding ids', () => {
    expect(index.datasetVersion).toBe('0.8.0');
    expect(index.all.length).toBe(95);
    expect(index.byId.size).toBe(95); // pins id-uniqueness of the shipped export
  });

  it('PROPERTY: assertion() is non-null IFF the claim is safe_to_assert (over all 95)', () => {
    for (const c of index.all) {
      const out = assertion(c);
      if (c.safe_to_assert && c.assertion_template.length > 0) {
        expect(out).toBe(c.assertion_template);
      } else {
        expect(out).toBeNull();
      }
      // Never serve raw claim_text as an assertion.
      if (out !== null) expect(out).toBe(c.assertion_template);
    }
  });

  // The 0.8.0 export currently ships ZERO unsafe claims, so the loop above never exercises the
  // false→null half of the IFF against real data. Pin that invariant (fail loud if a future
  // export ever ships an unsafe claim — exactly when the seam matters most) AND prove the
  // false branch holds on a real-shaped claim forced unsafe.
  it('PROPERTY (negative): every shipped claim is currently safe; forcing one unsafe → assertion null', () => {
    expect(index.all.every(c => c.safe_to_assert === true)).toBe(true);
    const forcedUnsafe = { ...index.all[0], safe_to_assert: false };
    expect(assertion(forcedUnsafe)).toBeNull();
    expect(assertion(forcedUnsafe)).not.toBe(forcedUnsafe.claim_text);
    // ...and the index would exclude it from the assertable set.
    const mixed = buildGroundingIndex({ dataset_version: '0.8.0', claims: [forcedUnsafe] });
    expect(allAssertableClaims(mixed)).toEqual([]);
  });

  it('every assertable claim carries a verification tier + citation (no fabrication)', () => {
    for (const c of allAssertableClaims(index)) {
      expect(c.verification_tier.length).toBeGreaterThan(0);
      expect(c.citation.length).toBeGreaterThan(0);
    }
  });

  it('indexes by concept and by id; lookups resolve', () => {
    const first = index.all[0];
    expect(claimById(index, first.grounding_id)).toBe(first);
    expect(claimsForConcept(index, first.concept_id)).toContain(first);
    expect(assertableClaimsForConcept(index, first.concept_id).every(isAssertable)).toBe(true);
  });

  it('claimById returns null for an unknown id', () => {
    expect(claimById(index, 'CG-NOPE')).toBeNull();
    expect(claimsForConcept(index, 'CK-NOPE')).toEqual([]);
  });
});

describe('buildGroundingIndex — malformed/empty input', () => {
  it('returns an empty index for null/missing claims (never throws)', () => {
    expect(buildGroundingIndex(null).all).toEqual([]);
    expect(buildGroundingIndex({ dataset_version: '0.8.0', claims: undefined as any }).all).toEqual([]);
    expect(buildGroundingIndex(null).datasetVersion).toBe('unknown');
  });

  it('drops malformed rows and de-dupes grounding_id (keeps first)', () => {
    const data: GroundingDataset = {
      dataset_version: '0.8.0',
      claims: [
        claim({ grounding_id: 'CG-1', claim_text: 'first' }),
        claim({ grounding_id: 'CG-1', claim_text: 'dupe' }),
        { grounding_id: 'CG-2' } as any, // malformed — missing required fields
        claim({ grounding_id: 'CG-3', safe_to_assert: false }),
      ],
    };
    const idx = buildGroundingIndex(data);
    expect(idx.all.map(c => c.grounding_id)).toEqual(['CG-1', 'CG-3']);
    expect(claimById(idx, 'CG-1')!.claim_text).toBe('first');
    expect(allAssertableClaims(idx).map(c => c.grounding_id)).toEqual(['CG-1']);
  });
});

describe('loadGroundingIndex — flag gating (byte-identical when OFF)', () => {
  beforeEach(() => __resetGroundingCacheForTests());

  it('returns null without loading the artifact when content flag is OFF', () => {
    mockFlag.mockReturnValue(false);
    expect(loadGroundingIndex()).toBeNull();
  });

  it('loads + indexes the bundled artifact when content flag is ON', () => {
    mockFlag.mockReturnValue(true);
    const idx = loadGroundingIndex();
    expect(idx).not.toBeNull();
    expect(idx!.datasetVersion).toBe('0.8.0');
    expect(idx!.all.length).toBe(95);
  });

  it('memoizes after first load', () => {
    mockFlag.mockReturnValue(true);
    const a = loadGroundingIndex();
    const b = loadGroundingIndex();
    expect(a).toBe(b);
  });
});
