/**
 * Quiz ingest integration (PR #5) — proves the bundled quiz sample pack flows end-to-end through the
 * real ContentStore pipeline: validate (incl. content_hash recomputation) → ingest (no quarantine) →
 * query by table → normalize → grade. This is the contract the QuizRunnerScreen relies on.
 */
import { createContentStore } from '../../../../content/contentStore';
import { createMemoryBackend } from '../../../../content/memoryBackend';
import { tableNameFor, type ContentPack } from '../../../../content/types';
import { normalizeQuestions, gradeAnswer } from '../../logic/quiz';

// The real bundled sample (generated by tools/content-export/make_quiz_sample.py, verbatim rows).
const samplePack = require('../../../../../assets/content/0.8.1/quiz_sample.pack.json') as ContentPack;

describe('bundled quiz sample → ContentStore → quiz logic', () => {
  it('validates and ingests WITHOUT quarantine (correct hash, self-contained FK)', async () => {
    const store = createContentStore(createMemoryBackend());
    const results = await store.ingest([samplePack]);
    expect(store.quarantine()).toEqual([]);
    expect(results).toHaveLength(1);
    expect(results[0]).toMatchObject({ ok: true, quarantined: false, table: 'quiz_bank' });
    expect(results[0].rows).toBe(samplePack.manifest.row_count);
  });

  it('table name matches and rows round-trip into valid questions', async () => {
    const store = createContentStore(createMemoryBackend());
    await store.ingest([samplePack]);

    const table = tableNameFor(samplePack.manifest.source_sheet);
    expect(table).toBe('quiz_bank');

    const rows = await store.getAll(table);
    expect(rows.length).toBe(samplePack.manifest.row_count);

    const questions = normalizeQuestions(rows);
    // Every shipped sample row is a well-formed question (no drops).
    expect(questions.length).toBe(rows.length);
    for (const q of questions) {
      expect(q.prompt.length).toBeGreaterThan(0);
      expect(q.options.some(o => o.key === q.correct)).toBe(true);
    }

    // Grading works against a real question.
    const first = questions[0];
    expect(gradeAnswer(first, first.correct).correct).toBe(true);
    const wrong = (['A', 'B', 'C', 'D'] as const).find(c => c !== first.correct)!;
    expect(gradeAnswer(first, wrong).correct).toBe(false);
  });

  it('find() by Category returns a subset', async () => {
    const store = createContentStore(createMemoryBackend());
    await store.ingest([samplePack]);
    const rows = await store.getAll('quiz_bank');
    const someCategory = String(rows[0].Category);
    const matched = await store.find('quiz_bank', { Category: someCategory });
    expect(matched.length).toBeGreaterThan(0);
    expect(matched.every(r => r.Category === someCategory)).toBe(true);
  });
});
